version: "3.9"

services:
  postgres-dev:
    image: postgres:15
    container_name: imobmatch_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: imobmatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
