# Database configuration
spring:
    datasource:
        url: ${DATASOURCE_URL}  # JDBC URL for the database
        driver-class-name: org.postgresql.Driver  # Database driver class
        username: ${DATASOURCE_USERNAME}  # Database username
        password: ${DATASOURCE_PASSWORD}  # Database password

    jpa:
        hibernate:
            ddl-auto: validate  # Validate schema on startup (does not modify DB)
        show-sql: false  # Disable SQL logging

# AWS S3 configuration
aws:
    region: ${AWS_REGION}  # AWS region
    access-key: ${AWS_ACCESS_KEY_ID}  # AWS access key ID
    secret-key: ${AWS_SECRET_ACCESS_KEY}  # AWS secret access key
    s3:
        public-base-url: https://%s.s3.amazonaws.com
        bucket:
            profile-photos: profile-photos  # Bucket for user profile photos
            property-images: property-images  # Bucket for property images


user:
    email:
        verified:
            default: false