# Database configuration
spring:
    datasource:
        url: ${DATASOURCE_URL}  # JDBC URL for the database
        driver-class-name: org.postgresql.Driver  # Database driver class
        username: ${DATASOURCE_USERNAME}  # Database username
        password: ${DATASOURCE_PASSWORD}  # Database password

    jpa:
        hibernate:
            ddl-auto: none  # Automatically update schema (use cautiously in prod)
        show-sql: true  # Show SQL statements in logs


# AWS S3 configuration
aws:
    region: ${AWS_REGION}  # AWS region
    access-key: ${AWS_ACCESS_KEY_ID}  # AWS access key ID
    secret-key: ${AWS_SECRET_ACCESS_KEY}  # AWS secret access key
    s3:
        endpoint: ${AWS_S3_ENDPOINT}
        public-base-url: ${AWS_S3_ENDPOINT}  # Custom S3 endpoint (optional)
        bucket:
            profile-photos: profile-photos  # Bucket for user profile photos
            property-images: property-images  # Bucket for property images

user:
    email:
        verified:
            default: true